name: Auto Build Gallery

on:
  workflow_dispatch:        # Manual trigger from GitHub
  push:
    branches: [ main ]     # Trigger only on main branch
    paths:
      - 'gallery/**'       # Only run if gallery folder changes

jobs:
  build-gallery:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout this submodule repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch full history (needed for pushing)

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Build gallery.json
      - name: Generate gallery.json
        run: |
          mkdir -p scripts
          cat <<'EOF' > scripts/build-gallery.mjs
          import fs from 'fs';
          import path from 'path';

          const root = './gallery';
          const out = './gallery.json';

          const folders = [];
          const images = [];

          function scan(dir, base = '') {
            for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
              const full = path.join(dir, entry.name);
              const rel = path.join(base, entry.name).replace(/\\/g, '/');

              if (entry.isDirectory()) {
                const cover = ['cover.jpg','cover.png','folder.jpg'].find(f =>
                  fs.existsSync(path.join(full, f))
                );
                folders.push({ name: entry.name, preview: cover ? rel + '/' + cover : null });
                scan(full, rel);
              } else if (/\.(png|jpe?g|gif|webp)$/i.test(entry.name)) {
                images.push({ name: entry.name, path: rel });
              }
            }
          }

          scan(root);

          fs.writeFileSync(out, JSON.stringify({ folders, images }, null, 2));
          console.log('✅ gallery.json created with', folders.length, 'folders and', images.length, 'images.');
          EOF

          node scripts/build-gallery.mjs

      # 4️⃣ Commit and push gallery.json
      - name: Commit and push changes
        run: |
          git config user.name "AutoGallery"
          git config user.email "actions@github.com"

          # Make sure we are on main branch (detached HEAD fix)
          git checkout main || git checkout -b main

          git add gallery.json

          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "Auto-update gallery.json"

          # Push changes
          git push origin main
