name: Auto Build Gallery

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/Gallery-App/gallery/**'  # watch nested gallery folder

jobs:
  build-gallery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build gallery.json
        run: |
          mkdir -p apps/Gallery-App/scripts
          echo "import fs from 'fs'; import path from 'path';
          const root='./apps/Gallery-App/gallery';
          const out='./apps/Gallery-App/gallery.json';
          function scan(dir,base=''){const folders=[],images=[];
          fs.readdirSync(dir,{withFileTypes:true}).forEach(e=>{
            const full=path.join(dir,e.name);
            const rel=path.join(base,e.name).replace(/\\\\/g,'/');
            if(e.isDirectory()){
              const cover=['cover.jpg','cover.png','folder.jpg'].find(f=>fs.existsSync(path.join(full,f)));
              folders.push({name:e.name,preview:cover?rel+'/'+cover:null});
            } else if(/\\.(png|jpe?g|gif|webp)$/i.test(e.name)){
              images.push({name:e.name,path:rel});
            }
          });
          return {folders,images};}
          fs.writeFileSync(out,JSON.stringify(scan(root),null,2));" > apps/Gallery-App/scripts/build-gallery.js
          node apps/Gallery-App/scripts/build-gallery.js

      - name: Commit and push updates
        run: |
          git config user.name "AutoGallery"
          git config user.email "actions@github.com"
          git add apps/Gallery-App/gallery.json
          git commit -m "Auto-update gallery.json" || echo "No changes"
          git push
